### PR TITLE
Use `previewPoints` on contract to compute APY

### LINKED ISSUE #342: Unexpected veOGV amount
I just went through the process of creating a new stake. I'm 99% sure that I was told I would receive ~830k veOGV, but [I ended up getting ~930k](https://etherscan.io/tx/0xd3360139c1a05653cd1731eb444f8bb632a1b336a2ade5c004c2e1c77e1e4525). I'll watch for this again next time I go through the experience. Let me know if someone else is able to reproduce it first.

### PR DESCRIPTION
**Pull request by shahthepro**
- Gets the veOGVReceived from contract (Fixes #342)
- Fixes under-reporting of APY calculation (Need someone to verify the APY)

### CODE REVIEW

File: client/utils/useStakingAPY.tsx [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+
+  const [loading, setLoading] = useState(true);
+  const [veOgvReceived, setVeOGVReceived] = useState(0);
+
+  const { totalSupplyVeOgvAdjusted } = totalBalances;
+
+  useEffect(() => {
+    if (!contracts.loaded) return;
+
+    let done = false;
```
Comment (smitch88) [inline client/utils/useStakingAPY.tsx:18]: Not familiar with this pattern for how you are using `done`, what are you trying to solve? Just running the `go` function once?

File: client/pages/claim.tsx [hunk 2]
```diff
@@ -41,9 +34,9 @@ const ClaimPage: NextPage<ClaimPageProps> = () => {
             The claim period has now expired
           </h2>
           <div className="mt-3 text-sm font-bold">
-            {`All unclaimed OGV was burned after 90 days. You can still buy OGV and stake it for up to four years. Current OGV stakers are earning a vAPY of ${stakingApy.toFixed(
-              2
-            )}%.`}
+            {`All unclaimed OGV was burned after 90 days. You can still buy OGV and stake it for up to four years. Current OGV stakers are earning a vAPY of ${
+              apyLoading ? "--.--" : stakingAPY.toFixed(2)
```
Comment (sparrowDom) [inline client/pages/claim.tsx:38]: nit: missing a % here. Should be:
```
apyLoading ? "--.--" : `${stakingAPY.toFixed(2)}%`
```

**Review by sparrowDom — APPROVED** [review]
great job at simplifying it and making it correct 💪

File: client/utils/useStakingAPY.tsx (hunk 1 above)
Comment (shahthepro) [reply client/utils/useStakingAPY.tsx:18]: Just defensive programming. `go` is an async function. It's possible that the component might rerender before the function completes execution. If it does, then `setState` will throw a bunch of console errors because it's trying to update state of a detached component. When the component demounts, done is set to true and the state isn't updated in that case

File: client/pages/claim.tsx (hunk 2 above)
Comment (shahthepro) [reply client/pages/claim.tsx:29]: Fixed. Thanks
